database:
  hostname: 
  portnmbr: 
  database: 
  username: 
  password:
  maxConnections: 5
cooldown: 30
top: 10
message:
  #can use <player> <karma> <reason>
  given: You have given karma to <player> for <reason>
  taken: You have taken karma from <player> for <reason>
  
  #can use <player> <admin> <karma> <reason>
  broadcastgive: <admin> has given <player> karma for <reason>.
  broadcasttake: <admin> has taken away karma from <player> for <reason>
  
  #can use <player> <admin>
  cooldown: You have tried to give/take <player> karma too soon.
  
  #can use <player>
  notfound: Could not find <player>.
  
  #can use <player> <karma>
  display: You have <karma> karma.
  view: <player> has <karma> karma.
  
  #can use <top>
  notop: Could not get top <top>
  
  #############################
  # Tags
  # <player> - Players name.
  # <admin> - admins name
  # <karma> - players karma
  # <top> - number of player to display with /karmatop
  # <reason> -  an optional reason for giving or taking karma. Will be 'null' if not used.
  #
  #
  
  #############################
  # Color Codes
  #		$0 = BLACK
  #		$1 = DARK_BLUE
  #		$2 = DARK_GREEN
  #		$3 = DARK_AQUA
  #		$4 = DARK_RED
  #		$5 = DARK_PURPLE
  #		$6 = GOLD
  #		$7 = GRAY
  #		$8 = DARK_GRAY
  #		$9 = BLUE
  #		$a = GREEN
  #		$b = AQUA
  #		$c = RED
  #		$d = LIGHT_PURPLE
  #		$e = YELLOW
  #		$f = WHITE
  #
  #