name: yeahKarma
main: mn.frd.yeahKarma.Karma
version: 0.4.2
author: frdmn
description: Reward players for being good. Punish players for being bad.
commands:
  karma:
    description: Display your karma
    usage: /karma [player]
    permission: karma.display
    permission-message: You don't have permission.
  karmagive:
    description: Give karma.
    usage: /karmagive <player> [reason]
    permission: karma.give
    permission-message: You don't have permission.
  karmatake:
    description: Take karma.
    usage: /karmatake <player> [reason]
    permission: karma.take
    permission-message: You don't have permission.
  karmatop:
    description: Display the top 10 players.
    usage: /karmatop
    permission: karma.top
    permission-message: You don't have permission.
permissions:
  karma.give:
    description: Allows a player to give out karma
    default: op
  karma.take:
    description: Allows a player to take karma away from others
    default: op
  karma.announcements:
    description: Show when a player receives karma
    default: true
  karma.top:
    description: Display the top 10 players
    default: true
  karma.display:
    description: Display your own karma
    default: true
  karma.view:
    description: Display others karma
    default: op
